[package]
name = "lmdb-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
eframe = "0.26.0"
egui_extras = "0.26.0"
egui_tiles = "0.7.2"
env_logger = "0.10.0"
heed = { version = "0.20.0", default-features = false, features = ["read-txn-no-tls"] }
stfu8 = "0.2.6"
